secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assumes that secrets are kept in local folder called ".secrets"
  db_root_pwd:
    file: .secrets/db_root_pwd.txt
  mysql_pwd:
    file: .secrets/db_pwd.txt
  mysql_db:
    file: .secrets/db_name.txt
  mysql_user:
    file: .secrets/db_user.txt
    
volumes:
  nextcloud-data:
  nextcloud-db:
  document_data:
  document_log:
  caddy_data:
  caddy_config:

services:
  nextcloud:
    container_name: nextcloud-app
    image: nextcloud:34-apache
    restart: unless-stopped
    expose:
      - '80'
    environment:
      - TRUSTED_PROXIES=caddy-server
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/mysql_pwd
      - POSTGRES_DB_FILE=/run/secrets/mysql_db
      - POSTGRES_USER_FILE=/run/secrets/mysql_user
      - OVERWRITEPROTOCOL=https
    secrets:
      - mysql_db
      - mysql_pwd
      - mysql_user
    volumes:
      - nextcloud-data:/var/www/html
      - /mnt/photos:/mnt/photos
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:17
    container_name: nextcloud-db
    restart: unless-stopped
    secrets:
      - mysql_db
      - mysql_pwd
      - mysql_user
    environment:
      POSTGRES_USER_FILE: /run/secrets/mysql_user
      POSTGRES_PASSWORD_FILE: /run/secrets/mysql_pwd
      POSTGRES_DB_FILE: /run/secrets/mysql_db
    volumes:
      - nextcloud-db:/var/lib/postgresql/data

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      #- JWT_SECRET=/run/secrets/onlyoffice_jwt_secret
      - JWT_HEADER=AuthorizationJwt
    #secrets:
      #- onlyoffice_jwt_secret
    env_file:
      - .secrets/onlyoffice_jwt_secret.env
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  caddy:
    image: caddy:2
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config